openapi: "3.0.0"
info:
  title: "Meal API"
  version: "2.0.0"
paths:
  /meals:
    get:
      summary: "Get a list of meals"
      parameters:
        - name: date
          in: query
          description: "Filter by dates"
          required: false
          schema:
            type: "array"
            items:
              type: "string"
        - name: location
          in: query
          description: "Filter by locations"
          required: true
          schema:
            type: "array"
            items:
              type: "string"
        - name: language
          in: query
          description: "Filter by language codes"
          required: false
          schema:
            type: "array"
            items:
              type: "string"
        - name: excludeAllergens
          in: query
          description: "List of allergen codes to exclude from the results"
          required: false
          schema:
            type: "array"
            items:
              type: "string"
        - name: vegan
          in: query
          description: "Filter if the meals are vegan"
          required: false
          schema:
            type: boolean
        - name: vegetarian
          in: query
          description: "Filter if the meals are vegetarian"
          required: false
          schema:
            type: boolean
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  last_updated:
                    type: "string"
                    description: "ISO Date of the last scrape from the website in UTC"
                  data:
                    type: array
                    items:
                      type: "object"
                      properties:
                        date:
                          type: "string"
                          description: "ISO Date (without time). E.g.: 2025-09-24"
                        name:
                          type: "string"
                        vegan:
                          type: "boolean"
                        price:
                          type: "object"
                          properties:
                            students:
                              type: "number"
                            employees:
                              type: "number"
                            guests:
                              type: "number"
                        vegetarian:
                          type: "boolean"
                        location:
                          type: object
                          properties:
                            name:
                              type: "string"
                            code:
                              type: "string"
                            city:
                              type: "string"
                        allergens:
                          type: "array"
                          items:
                            type: "object"
                            properties:
                              code:
                                type: "string"
                              name:
                                type: "string"
                        language: 
                          type: "object"
                          properties:
                            code: 
                              type: "string"
                              description: "The ISO 639 language code"
                            name: 
                              type: "string"
                              description: "The native name of the language"

  /allergens:
    get:
      summary: "Get a list of allergens"
      parameters:
        - name: code
          in: query
          description: "Filter by allergen codes"
          required: false
          schema:
            type: "array"
            items:
              type: "string"
        - name: name
          in: query
          description: "Filter by allergen names"
          required: false
          schema:
            type: "array"
            items:
              type: "string"
        - name: language
          in: query
          description: "Filter by language codes"
          required: false
          schema:
            type: "array"
            items:
              type: "string"
        - name: location
          in: query
          description: "Filter by locations"
          required: true
          schema:
            type: "array"
            items:
              type: "string"
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  last_updated:
                    type: "string"
                  data:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        code:
                          type: "string"
                        name:
                          type: "string"
                        language: 
                          type: "object"
                          properties:
                            code: 
                              type: "string"
                              description: "The ISO 639 language code"
                            name: 
                              type: "string"
                              description: "The native name of the language"

  /locations:
    get:
      summary: "Get a list of locations"
      parameters:
        - name: code
          in: query
          description: "Filter by location codes"
          required: false
          schema:
            type: "array"
            items:
              type: "string"
        - name: city
          in: query
          description: "Filter by city"
          required: false
          schema:
            type: "array"
            items:
              type: "string"
        - name: name
          in: query
          description: "Filter by location names"
          required: false
          schema:
            type: "array"
            items:
              type: "string"
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  last_updated:
                    type: "string"
                  data:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        code:
                          type: "string"
                        name:
                          type: "string"
                        city:
                          type: "string"
                        available_languages:
                          type: "object"
                          properties:
                            code: 
                              type: "string"
                              description: "The ISO 639 language code"
                            name: 
                              type: "string"
                              description: "The native name of the language"
