apiVersion: apps/v1
kind: Deployment
metadata:
  name: speiseplan
  namespace: simple-tools
  labels:
    app: speiseplan
    commit: "{{ UNIQUE_TAG }}"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: speiseplan
  template:
    metadata:
      labels:
        app: speiseplan
        commit: "{{ UNIQUE_TAG }}"
    spec:
      containers:
      - image: "ghcr.io/draculente/mensa-api:master"
        name: speiseplan
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}
      imagePullSecrets:
      - name: "dockerconfigjson-github-com"