apiVersion: apps/v1
kind: Deployment
metadata:
  name: speiseplan-old
  namespace: speiseplan
  labels:
    app: speiseplan-old
    commit: "{{ UNIQUE_TAG }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speiseplan-old
  template:
    metadata:
      labels:
        app: speiseplan-old
        commit: "{{ UNIQUE_TAG }}"
    spec:
      containers:
        - image: "ghcr.io/draculente/mensa-api:master"
          name: speiseplan-old
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "50m"
              memory: "200Mi"
            limits:
              cpu: "150m"
              memory: "250Mi"
      imagePullSecrets:
        - name: "dockerconfigjson-github-com"
