kind: Service
apiVersion: v1
metadata:
  name: speiseplan-service-old
  namespace: speiseplan
spec:
  selector:
    app: speiseplan-old
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
